[phases.setup]
nixPkgs = ['nodejs-20_x']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'HOST=0.0.0.0 PORT=3000 node ./dist/server/entry.mjs'

[variables]
NODE_ENV = 'production'
HOST = '0.0.0.0'
PORT = '3000'
